In [1]:
import nltk
from nltk.corpus import brown
##corpora-set of the sentences

In [2]:
brown

<CategorizedTaggedCorpusReader in 'C:\\Users\\KIIT\\AppData\\Roaming\\nltk_data\\corpora\\brown'>

In [3]:
brown?

In [6]:
print(brown.categories())

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']


In [18]:
data=brown.sents(categories="adventure")
data

[['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.'], ['He', 'was', 'well', 'rid', 'of', 'her', '.'], ...]

In [11]:
print(len(data))

4637


In [12]:
data[0]
#the first sentence that is present in the brown corpus

['Dan',
 'Morgan',
 'told',
 'himself',
 'he',
 'would',
 'forget',
 'Ann',
 'Turner',
 '.']

In [15]:
' '.join(data[0])
#as you can see we have joined the letters that were present inside the corpu

'Dan Morgan told himself he would forget Ann Turner .'

    Bags of word pipeline
    the work of this pipeline is to covert the text data into the numeric data.we can use other classfication algo also to classify the data but we use the nlp because of the bag of words pipeline
    
    Text->numbers->classifier

In [19]:
document="""It was a very pleasant day. The weather was cool and there were light showers. I went to market to buy some fruits"""
sentence="Send all the 50 documents related to chapters 1,2,3 to shivam@gmail.com"
text = "God is Great! I won a lottery."


In [23]:
##Tokenisation/Stopword Removal
from nltk.tokenize import sent_tokenize,word_tokenize
sent=sent_tokenize(document)
sent

['It was a very pleasant day.',
 'The weather was cool and there were light showers.',
 'I went to market to buy some fruits']

In [24]:
print(len(sent))

3


In [25]:
sent[0]

'It was a very pleasant day.'

In [28]:
word=word_tokenize(sentence)
print(word)

['Send', 'all', 'the', '50', 'documents', 'related', 'to', 'chapters', '1,2,3', 'to', 'shivam', '@', 'gmail.com']


In [30]:
word[0]

'Send'

In [31]:
print(len(word))

13


In [35]:
from nltk.corpus import stopwords
sw=set(stopwords.words('english') )

In [36]:
print(sw)

{'now', 'has', 'herself', "isn't", 'few', 're', "it's", 'than', 'too', 'wouldn', 'isn', "you'll", 'when', 'about', 'my', 'or', 'he', 'she', 'some', 'himself', 'ourselves', 'didn', 'be', 'nor', 't', 'your', 'its', 'between', 'mustn', "mustn't", 'at', 'before', 'after', 'if', 'y', 'i', "you'd", 'are', 'had', "haven't", 'couldn', 'our', 'weren', 'can', 'hadn', 'for', "weren't", 'theirs', 'over', 'a', 'against', 'just', 'during', 'the', 'have', 'only', 'own', 'yours', 'which', 'them', 'but', 'then', "wasn't", 'all', "she's", 'themselves', 'we', 'am', 'having', 'by', 'him', "wouldn't", 'who', 'hasn', 'that', 'don', 'does', 'out', 'of', "you've", 'o', 'most', 've', 'while', 'ours', 'his', "needn't", 'myself', 'an', 'do', 'me', "shouldn't", 'in', 'down', "didn't", 'because', 'as', 'on', 'should', 'itself', 'it', 'doing', 'through', "don't", 'shan', 'again', 'same', 'those', 'is', "won't", 'won', 'ain', 'this', 'were', 'yourselves', 'other', 'not', 'where', 'd', 'ma', 'until', 'why', 'll', "sh

In [39]:
def remove_stopwords(text,stopwords):
    useful_words=[w for w in text if w not in stopwords]
    return useful_words

In [43]:
text="I am very intelligent and you are dumb".split()

In [44]:
useful_text=remove_stopwords(text,sw)
print(useful_text)

['I', 'intelligent', 'dumb']


In [45]:
sentence="send all the 50 documents related to chapter 1,2,3 to shivam@gmail.com"

In [46]:
from nltk.tokenize import RegexpTokenizer

In [47]:
tokenizer=RegexpTokenizer('[a-zA-z]+')
useful_text=tokenizer.tokenize(sentence)

In [48]:
useful_text

['send',
 'all',
 'the',
 'documents',
 'related',
 'to',
 'chapter',
 'to',
 'shivam',
 'gmail',
 'com']

In [49]:
tokenizer=RegexpTokenizer('[a-zA-z@]+')
useful_text=tokenizer.tokenize(sentence)

In [50]:
useful_text

['send',
 'all',
 'the',
 'documents',
 'related',
 'to',
 'chapter',
 'to',
 'shivam@gmail',
 'com']

In [51]:
#there are three types of the stemmer:snowball stemmer,porter stemmer,lancaster stemmer
#the special thing about the snowball stemmer is that it is multilanguage stemmer it also supports some of the language like french,german etc
from nltk.stem.snowball import SnowballStemmer,PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

In [53]:
ps=PorterStemmer()
ps.stem('jumping')

'jump'

In [54]:
ps.stem('jumps')

'jump'

In [55]:
ls=LancasterStemmer()

In [56]:
ls.stem('jumping')

'jump'

In [59]:
ls.stem('jumps')

'jump'

In [60]:
ps.stem('lovely')

'love'

In [61]:
ps.stem('loving')

'love'

In [62]:
sn=SnowballStemmer('english') #in the snowball stemmer it is nescssary to give the arguement if we dont give the arguement then the snowball stemmer will not work

In [63]:
sn.stem('lovely')

'love'

In [64]:
sn.stem('jump-ing')
#in this case it is not maching with the any word so it is the basic rule that if at the end there is ing then the ing will be removed

'jump-'

In [68]:
#SAMPLE CORPUS-CONTAINS 4 DOCUMEENTS AND EACH IF THE DOCUMENT HAS ONE OR MORE THAN ONE SENTENCES
corpus=['Indian cricket team will win the world cup says the capt.Virat kohli.World cup will held in Srilanka.',
       'We will win the next loksabha election says the confident Indian PM.',
       'The nobel laurate won the hearts of people.',
       'The movie raazi is an exciting Indian spy thriller based upon the real story.']

In [65]:
#the vectors tell us what word is appearing how many number of times
from sklearn.feature_extraction.text import CountVectorizer

In [66]:
cv=CountVectorizer()

In [69]:
vectorized_corpus=cv.fit_transform(corpus)
#the fit_transform will convert it into the vector

In [70]:
vectorized_corpus
#as you can see it is a sparse matrix

<4x38 sparse matrix of type '<class 'numpy.int64'>'
	with 46 stored elements in Compressed Sparse Row format>

In [72]:
print(vectorized_corpus )
#it means in the zeroth sentence the first word is getting the index of 11 in the dictionary and value at that index is 1
#simpilarly we can see for the other words in the sentences

  (0, 26)	1
  (0, 10)	1
  (0, 9)	1
  (0, 13)	1
  (0, 32)	1
  (0, 2)	1
  (0, 24)	1
  (0, 5)	2
  (0, 37)	2
  (0, 29)	2
  (0, 35)	1
  (0, 34)	2
  (0, 28)	1
  (0, 4)	1
  (0, 11)	1
  (1, 21)	1
  (1, 3)	1
  (1, 6)	1
  (1, 15)	1
  (1, 17)	1
  (1, 33)	1
  (1, 24)	1
  (1, 29)	2
  (1, 35)	1
  (1, 34)	1
  (1, 11)	1
  (2, 20)	1
  (2, 19)	1
  (2, 8)	1
  (2, 36)	1
  (2, 14)	1
  (2, 18)	1
  (2, 29)	2
  (3, 27)	1
  (3, 23)	1
  (3, 31)	1
  (3, 1)	1
  (3, 30)	1
  (3, 25)	1
  (3, 7)	1
  (3, 0)	1
  (3, 12)	1
  (3, 22)	1
  (3, 16)	1
  (3, 29)	2
  (3, 11)	1


In [74]:
vectorized_corpus=vectorized_corpus.toarray()

In [75]:
print(vectorized_corpus)

[[0 0 1 0 1 2 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 2 0 0 1 0 2 1 0
  2]
 [0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 2 0 0 0 1 1 1 0
  0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1
  0]
 [1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 2 1 1 0 0 0 0 0
  0]]


In [77]:
cv.vocabulary_
#which word is getting which index in the vocab

{'an': 0,
 'based': 1,
 'capt': 2,
 'confident': 3,
 'cricket': 4,
 'cup': 5,
 'election': 6,
 'exciting': 7,
 'hearts': 8,
 'held': 9,
 'in': 10,
 'indian': 11,
 'is': 12,
 'kohli': 13,
 'laurate': 14,
 'loksabha': 15,
 'movie': 16,
 'next': 17,
 'nobel': 18,
 'of': 19,
 'people': 20,
 'pm': 21,
 'raazi': 22,
 'real': 23,
 'says': 24,
 'spy': 25,
 'srilanka': 26,
 'story': 27,
 'team': 28,
 'the': 29,
 'thriller': 30,
 'upon': 31,
 'virat': 32,
 'we': 33,
 'will': 34,
 'win': 35,
 'won': 36,
 'world': 37}

In [78]:
def mytokenizer(document):
    words=tokenizer.tokenize(document.lower())
    #remove stopwords
    words=remove_stopwords(words,sw)
    return words

In [79]:
mytokenizer('this is some fuction')

['fuction']

In [80]:
cv=CountVectorizer(tokenizer=mytokenizer)

In [81]:
vectorized_corpus=cv.fit_transform(corpus).toarray()

In [82]:
print(vectorized_corpus)

[[0 1 0 1 2 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 2]
 [0 0 1 0 0 1 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 1 1 0 0 0]]


In [86]:
##test data
test_corpus=["Indian are very great"]
cv.transform(test_corpus).toarray()
#if you fit_transform while using the test data then it will create the problem

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [87]:
sent_1=['this is good movie']
sent_2=['this is good movie but actor is not present']
sent_3=['this is not good movie']

In [89]:
cv=CountVectorizer(ngram_range=(1,3))
docs=[sent_1[0],sent_2[0]]
cv.fit_transform(docs).toarray()

array([[0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [90]:
sent_1='this is a good movie'
sent_2='this was good movie'
sent_3='this is not good movie'

In [91]:
corpus=[sent_1,sent_2,sent_3]

In [92]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [93]:
tfidf=TfidfVectorizer()

In [94]:
vc=tfidf.fit_transform(corpus).toarray()

In [95]:
print(vc)

[[ 0.46333427  0.59662724  0.46333427  0.          0.46333427  0.        ]
 [ 0.41285857  0.          0.41285857  0.          0.41285857  0.69903033]
 [ 0.3645444   0.46941728  0.3645444   0.61722732  0.3645444   0.        ]]


In [96]:
tfidf.vocabulary_
#we can see from the above the word that is occuring very less has very low weight

{'good': 0, 'is': 1, 'movie': 2, 'not': 3, 'this': 4, 'was': 5}

In [97]:
from nltk import word_tokenize
sent = "Hey! Welcome to the worlds of wonder?."
words = set(word_tokenize(sent))
print(words)

{'Hey', '.', 'wonder', '!', 'Welcome', 'worlds', 'to', 'the', 'of', '?'}
